services:
  jenkins:
    build: ./imagenes/jenkins/.
    container_name: jenkins
    restart: unless-stopped 
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ${JENKINS_DATA_PATH}/jenkins_home:/var/jenkins_home
      - ${JENKINS_DATA_PATH}/var/run/docker.sock:/var/run/docker.sock
      - ${JENKINS_DATA_PATH}/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ${JENKINS_DATA_PATH}/jenkins.yaml:/var/jenkins_home/casc.yaml
    environment:
      - TZ=America/Santiago
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml  # Habilita JCasC

volumes:
  jenkins_home:

