#version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt  # Plugins automáticos
      - ./jenkins.yaml:/var/jenkins_home/casc.yaml  # Configuración como código
    environment:
      - TZ=America/Santiago
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml  # Habilita JCasC

volumes:
  jenkins_home: